---
# A Demo section created with the Blank widget.
# Any elements can be added in the body: https://sourcethemes.com/academic/docs/writing-markdown-latex/
# Add more sections by duplicating this file and customizing to your requirements.

widget: "blank"  # See https://sourcethemes.com/academic/docs/page-builder/
headless: true  # This file represents a page section.
active: true # Activate this widget? true/false
weight:  21  # Order that this section will appear.

title: "Statistics"
subtitle: "Record how many work I have done"

design:
  # Choose how many columns the section has. Valid values: 1 or 2.
  columns: "1"
---

```{r, include = FALSE}
library(tidyverse)
library(rvest)
library(lubridate)
library(ggplot2)
```

```{r, include = FALSE, cache = FALSE}
# Get GitHub contributions
html <- xml2::read_html("https://github.com/jaspershen")
calendar <- html_node(html, ".js-calendar-graph-svg")
calendar_days <- html_nodes(calendar, "rect")
gh_data <- tibble(
  date = as.Date(xml_attr(calendar_days, "data-date")),
  count = xml_attr(calendar_days, "data-count"),
  type = "github",
  tip = str_glue("{count} contributions"),
  link = str_glue("https://github.com/jaspershen?from={date}&to={date}&tab=overview")
)
```

```{r, include = FALSE}
## get posts
posts <- list.files(
  here::here("content/en/post"),
  recursive = TRUE,
  full.names = FALSE,
  pattern = "^index[.]R?md"
)
post_data <-
  map_dfr(set_names(posts, dirname(posts)), function(file) {
    data <-
      rmarkdown::yaml_front_matter(here::here("content/en/post", file))
    list(
      date = as.Date(data$date),
      title = data$title,
      is_video = isTRUE(data$video)
    )
  }, .id = "dir") %>%
  mutate(
    type = ifelse(is_video, "video", "post"),
    link = file.path("post", dir),
    tip = title
  ) %>%
  dplyr::select(-is_video)
```

```{r, include = FALSE}
## Get talks and workshops
talks <- list.files(here::here("content/en/talk"), recursive = TRUE, full.names = FALSE, pattern = "^index[.]md")
talk_data <- map_dfr(set_names(talks, dirname(talks)), function(file) {
  data <- rmarkdown::yaml_front_matter(here::here("content/en/talk", file))
  list(
    date = as.Date(data$date),
    title = data$title,
    is_workshop = "workshop" %in% data$tags
  )
}, .id = "dir") %>%
  mutate(
    type = ifelse(is_workshop, "workshop", "talk"),
    link = file.path("talk", dir),
    tip = title
  ) %>%
  dplyr::select(-is_workshop)
```

```{r, include = FALSE, cache = FALSE}
## Get pkg releases
# get_pkgs <- function(emails, size = 100) {
#   emails <- glue::glue_collapse(glue::double_quote(emails), ",")
#   url <- str_glue("http://crandb.r-pkg.org/-/maintainer?keys=[{emails}]")
#   res <- jsonlite::read_json(url)
#   map_chr(res, 2L)
# }
# get_releases <- function(data) {
#   out <- map(set_names(data), ~ crandb::package(.x, "all"))
#   map_dfr(out, ~ list(version = names(.x$timeline), date = readr::parse_datetime(map_chr(.x$timeline, function(y) y %||% NA_character_))), .id = "package")
# }
# pkg_data <- get_releases(get_pkgs(c("james.f.hester@gmail.com", "jim.hester@rstudio.com", "james.hester@rstudio.com"))) %>%
#   mutate(
#     type = "pkg",
#     link = str_glue("https://CRAN.R-project.org/package={package}"),
#     tip = str_glue("{package}: {version}"),
#     date = as.Date(date)
#   )
```

```{r, include = FALSE}
## Join all data together
all_data <- bind_rows(
  dplyr::select(
    dplyr::filter(gh_data, as.numeric(count) > 0),
    date,
    type,
    tip,
    link,
    count
  ),
  dplyr::select(talk_data, date, type, tip, link),
  # select(pkg_data, date, type, tip, link),
  dplyr::select(post_data, date, type, tip, link)
)
empty_days <-
  dplyr::filter(gh_data, count == 0, !(date %in% all_data$date)) %>%
  dplyr::mutate(type = NA) %>%
  dplyr::select(date, type)
all_data <- bind_rows(all_data,
                      empty_days)
```

```{r, echo = FALSE, message = FALSE, warning = FALSE}
## prepare data for plots
last_year <- today() - years(1)
p_data <- dplyr::filter(all_data, date >= last_year, date <= today()) %>%
  dplyr::mutate(
    x = floor_date(date, "week"),
    y = fct_rev(lubridate::wday(date, label = TRUE)),
    # type = factor(type, levels = c("github", 
    #                                # "video", 
    #                                "post"
    #                                # "talk", 
    #                                # "workshop"
    #                                )),
    on_click = str_glue('window.location.assign("{link}")'),
    data_id = ifelse(!is.na(type), as.character(seq_along(x)), NA_character_),
    tip = str_glue("<b>{tip}</b> on {date}")
  )
counts <- dplyr::count(p_data, type, .drop = FALSE) %>%
  na.omit() %>%
  dplyr::mutate(
    n = case_when(
      type == "github" ~ dplyr::count(na.omit(p_data), type, wt = as.integer(count)) %>% 
        dplyr::pull(),
      TRUE ~ n
    ),
    emoji = c("💻",
              # "📹", 
              "📋"
              # "📽", 
              # "⚒" 
              ) ,
    nice = c("GitHub",
             "posts"
             ),
    label = str_glue("{scales::comma_format(accuracy = 1)(n)} {emoji}\n{nice}")
  )
###
library(ggthemes)
###
```

```{r, echo = FALSE, warning = FALSE}
# p_data$count[is.na(p_data$count)] <- 0
## Actually plot
my_pal = solarized_pal("green")(5)
rebase <- ggthemes:::solarized_rebase()
library(ggiraph)
p <- ggplot() +
  geom_tile(
    data = dplyr::filter(p_data, is.na(type)),
    width = 6,
    height = .8,
    aes(x, y, fill = type),
    key_glyph = draw_key_point
  ) +
  geom_tile_interactive(
    # ggplot2::geom_tile(
    data = dplyr::filter(p_data, !is.na(type)),
    width = 6,
    height = .8,
    aes(
      x,
      y,
      fill = type,
      alpha = log(as.numeric(count)),
      tooltip = tip,
      onclick = on_click,
      data_id = data_id
    )
    # key_glyph = draw_key_point
  ) +
  scale_fill_manual(
    values = c(
      "github" = my_pal[[1]],
      # "video" = my_pal[[2]],
      "post" = my_pal[[3]]
      # "talk" = my_pal[[4]],
      # "workshop" = my_pal[[5]]
    ),
    breaks = c("github", 
               # "video",
               "post"
               # "talk",
               # "workshop"
               ),
    labels = counts$label,
    na.translate = TRUE,
    na.value = "#eee8d5"
  ) +
  scale_y_discrete(breaks = c("Mon", "Wed", "Fri")) +
  theme_bw() +
  theme(
    rect = element_rect(fill = "transparent"),
    line = element_blank(),
    panel.background = element_rect(fill = "transparent",colour = NA),
    plot.background = element_rect(fill = "transparent",colour = NA),
    # text = element_text(family = "Lato", size = 7),
    legend.position = "right",
    aspect.ratio = .8 / 6
  ) +
  guides(
    alpha = "none",
    fill = guide_legend(
      title = NULL,
      override.aes = list(shape = 'square filled', size = 1),
      keywidth = 1,
      # label.theme = element_text(family = "Lato", size = 7),
      label.position = "right",
      nrow = 2
    )
  ) +
  labs(x = NULL, y = NULL)
x <- girafe(code = print(p),
            width_svg = 6,
            height_svg = 2)
##
tooltip_css <-
  "background: #ffffff; opacity: 1; color: #839496; border-radius: 5px;
                padding: 5px; box-shadow: 3px 3px 5px 0px #888888;
                font-size: 12px; border-width 2px; border-color: #002b36;"
##
girafe_options(x, opts_tooltip(css = tooltip_css))
```



```{r, echo = FALSE, warning = FALSE, out.width="100%", fig.asp = 0.6}
#
library(scholar)
library(ggplot2)
cit <- get_citation_history('3TK9yz8AAAAJ')
if(nrow(cit) < 8){
  year <- cit[1,1]
  cit1 <- 
    matrix(rep(c(year - 1, 0), 8 - nrow(cit)), 
                      ncol = 2, byrow = TRUE)
  cit1[,1] <- cit1[,1] - c(0:(nrow(cit1) - 1))
  colnames(cit1) <- colnames(cit)
  cit <- rbind(cit1,
               cit) %>% 
    as.data.frame() %>% 
    dplyr::arrange(year)
}
# profile <- scholar::get_profile("3TK9yz8AAAAJ")
plot <- 
ggplot(cit, aes(x = year, y = cites)) +
  geom_bar(stat = "identity", fill = ggplot2::alpha("#991500", 0.8)) +
    xlab('Year of citation')+
    ylab('Google Scholar\n cites') +
    theme_void() +
  ggplot2::ggtitle("Google Scholar") +
  theme(
    rect = element_rect(fill = "transparent", color = "#991500"),
    title = element_text(colour = "#991500"),
    axis.text = element_text(color = "#991500"),
    axis.title = element_text(color = "#991500"),
    axis.ticks = element_line(color = "#991500"),
    line = element_blank(),
    panel.background = element_rect(fill = "transparent", colour = "#991500"),
    plot.background = element_rect(fill = "transparent",
                                   colour = NA)) 

# table <- data.frame(All = c(profile$total_cites,
# profile$h_index,
# profile$i10_index))

# rownames(table) <- c("Citations", "h-index", "i10-index")

plotly::ggplotly(plot)
# knitr::kable(table, format = 'html')
```