---
title: 怀孕基础知识总结
author: Xiaotao Shen
date: '2019-11-01'
slug: ''
categories:
  - literature
tags:
  - Academic
image:
  caption: ''
  focal_point: ''
output:
  blogdown::html_page:
    toc: true
    number_sections: true
---

因为要做跟怀孕相关的项目,所以把一些基础的怀孕知识做一下总结.

# 孕龄(gestational age,GA)的计算

整个怀孕周期为280天.10个妊娠月(每个妊娠月为28天).孕妇在妊娠38-42周内分娩,均为足月.由于每位女性月经周期长短不一,所以推测的预产期与实际预产期有1-2周的出入也是正常的.主要的计算方法有以下几种:

1. 根据末次月经计算:

末次月经日期(第一天)的月份加9或减3,为预产期月份数;天数加7,为预产期日.例如:张女士的末次月经是2008年3月13日,其预产期约为:2008年12月20日.李女士的末次月经是2008年5月28日,其预产期约为:2009年3月5日.也可以从末次月经第一天起向后推算到第280天就是预产期.

2. 根据胎动日期计算:

如不清末次月经日期,可以依据胎动日期来进行推算.一般胎动开始于怀孕后的18-20周.计算方法为:初产妇是胎动日加20周;经产妇是胎动日加22周.

3. 根据基础体温曲线计算:

将基础体温曲线的低温段的最后一天作为排卵日,从排卵日向后推算264-268天,或加38周.

4. 根据B超检查推算:

医生做B超时测得胎头双顶间径,头臀长度及股骨长度即可估算出胎龄,并推算出预产期(此方法大多作为医生B超检查诊断应用).

用来预测胎儿体重(fetal birth weight)的几个参数(从超声波测量而来):

* Fiparietal diameter(BPD):胎儿双顶径.为两侧顶骨隆突间的距离,是胎头最大横径,临床用B型超声检测此值判断胎儿大小,妊娠足月时平均长度约9.3cm.

* Femur length(FL):胎儿股骨长度.

* Head circumference (AC):胎儿头围.

* Abdominal circumference (AC):胎儿腹围.

* crown–rump length:胎儿的头臀长.

5. 从孕吐开始的时间推算:

反应孕吐一般出现在怀孕6周末，就是末次月经后42天，由此向后推算至280天即为预产期。


