---
title: pregnancy project文献阅读总结
author: Xiaotao Shen
date: '2019-10-11'
slug: pregnancy-project
categories:
  - literature
tags:
  - Academic
image:
  caption: ''
  focal_point: ''
output:
  blogdown::html_page:
    toc: true
    number_sections: true
---

# Google key work search

## Urinary metabolic variation analysis during pregnancy and application in Gestational Diabetes Mellitus and spontaneous abortion biomarker discovery

https://www.ncbi.nlm.nih.gov/pmc/articles/PMC6384939/pdf/41598_2019_Article_39259.pdf

LC-MS urine metabolomics, 50 health pregant women. 3 time points. Age, BMI, parity and gravity (引力). Additionally, urine metabolomics was applied for early prediction of two pregnancy complications(并发症), gestational diabetes mellitus(妊娠期糖尿病) and spontaneous abortion(自然流产).

Our results suggested that during normal pregnancy progression, pathways of **steroid hormone biosynthesis and tyrosine metabolism** were signifcantly regulated.


First, second and third trimester:

妊娠期是指受孕后至分娩前的生理时期，属生理学名词，亦称怀孕期。自成熟卵受精后至胎儿娩出，一般为266天左右。为便于计算，妊娠通常是从末次月经第一天算起，足月妊娠约为280天(40周)。在妊娠期间母体的新陈代谢、消化系统、呼吸系统、血管系统、神经系统、内分泌系统、生殖系统、骨关节韧带及乳房均发生相应的改变。妊娠期全过程共分为3个时期：妊娠13周末以前称早期妊娠(First trimester)；第14～27周末称中期妊娠(Second trimester)；第28周及其后称晚期妊娠(Third trimester)。

MetPA pathway analysis showed that steroid hormone biosynthesis was upregulated in healthy controls during pregnancy with a high impact. Tyrosine metabolism was down-regulated with less impact (Fig. 2c).


BMI and other clinical factor correlation with metabolome.

Waters ACQUITY H-class LC system coupled with an LTQ-Orbitrap mass spectrometer (Thermo Fisher Scientific, Villebon-sur-Yvette, France).

**It is also RPLC column**

Waters HSS C18 column (3.0 × 100 mm, 1.7 μm) at a flow rate of 0.3 ml/min. Mobile


## Metabolic profiling of pregnancy: cross- sectional and longitudinal evidence

The aim of this study is to comprehensively characterise the maternal systemic metabolism across a wide range of metabolic and inflammatory measures in both cross-sectional and longitudinal settings coupled with with replication.

This is a serum based study.

## Maternal urinary metabolic signatures of fetal growth and associated clinical and environmental factors in the INMA study

使用NMR仪器采集urine数据.一共两个cohort.两个时间点(fisrt and third trimesters of gestation).用metabolome来预测fetal growth和birth weight.

测到的东西包括:branched-chain amino acids(支链氨基酸);isoleucine(异亮氨酸),valine(颉氨酸),leucine(亮氨酸),alanine(丙氨酸)和3 hydroxyisobutyrate(羟基异丁酸)(metabolite of valine).

另外一大类就是:pregnancy-related hormone by-products of estrogens and progesterone, and the methyl donor choline.
Physical activity, as well as other modifiable lifestyle/clinical factors, such as coffee consumption, vitamin D intake, and smoking, were identified as potential sources of metabolic variation during pregnancy.First trimester metabolic phenotypes could not predict reproducibly weight at later stages of development. 

### 结论

Significant reproducible maternal urinary metabolic signatures of fetal growth and birth weight are identified for the first time and linked to modifiable lifestyle factors. This novel approach to prenatal(产前的) screening, combining multiple risk factors, present a great opportunity to personalize pregnancy management management and reduce newborn disease risk in later life.


NMR采集数据,一共1695 metabolic phenotypes.

This is good study.

Exploratory metabolic profiling offers a powerful means of capturing systems-level information that re- flects both maternal genetic and environmental influ- ences, hence helping to elucidate metabolic disturbances and pathways associated with fetal outcomes.

This study aimed to (1) characterize the maternal urinary metabolome throughout pregnancy, (2) identify maternal metabolic signatures of fetal growth in two subcohorts, (3) explain potential sources of variation in metabolic profiles based on lifestyle and clinical data, and finally (4) to determine the individ- ual importance of metabolic signatures versus other maternal


### Study population

The women were interviewed twice during pregnancy (in the first and third trimesters of gestation) to obtain infor- mation about their sociodemographic characteristics and lifestyle variables. The urine samples were collected in the same interview in the morning (spot samples). The urine samples were collected in the same interview in the morning (spot samples). 所以一共有两个时间点.分别在first trimester and third trimesters.时间为12.4 ± 1.2 and 33.9 ± 1.3 weeks.

### Definition of the fetal and birth measurements

Fetal growth scores or standard deviation scores (z- scores) were obtained using longitudinal growth curves calculated for each individual adjusting for constitutional factors known to affect fetal growth (i.e., maternal age, height, parity, pre-pregnancy weight, country of origin, father’s height, and fetal sex).

Fetal growth score是使用longitudinal growth curve来计算的,然后adjust了一些已知的能够影响fetal growth的因素,如maternal age(母亲的年龄),height(母亲的身高),parity(已生胎数),pre-pregnancy weight(怀孕前的体重),country of origin(地区),father’s height(母亲的身高),and fetal sex(胎儿性别).

这个值是一个标准化后的值.(standard deviation scores,z-scores).

没有矫正后的z-score.

Anthropometric measures at birth included body weight and placental weight and were scaled to z-scores by subtracting the mean and dividing by the standard deviation. For further details on phenotype measurements and covariate definitions, such as gestational age, see Additional file 1: Supplementary Methods and a pre- vious article on the INMA cohort [13].
Metabolic

用来预测胎儿体重(fetal birth weight)的几个参数(从超声波测量而来):

* Fiparietal diameter(BPD):胎儿双顶径.为两侧顶骨隆突间的距离,是胎头最大横径,临床用B型超声检测此值判断胎儿大小,妊娠足月时平均长度约9.3cm.

* Femur length(FL):胎儿股骨长度.

* Head circumference (AC):胎儿头围.

* Abdominal circumference (AC):胎儿腹围.

* crown–rump length:胎儿的头臀长.



date of conception:妊娠期.

Gestational age(孕龄)was established by using crown–rump length when the calculated date of conception differed from the fetal age based on the subject’s self-reported last menstrual period by 7 days or more.


## Variants in the fetal genome near pro-inflammatory cytokine genes on 2q13 associate with gestational duration

* 早产(preterm birth),是指在妊娠不足37周出生的婴儿.早产与婴儿之后的神经发育延迟(neurodevelopmental delay),脑瘫(cerebral palsy),糖尿病(diabetes),高血压以及精神疾病(psychiatric disorders)等都有关.

* 过期生产(postterm birth),是指在妊娠超过42周之后出生的婴儿.

在发达国家,preterm和postterm都有大约5%-10%的比例.在低收入和中等收入国家,preterm的比例比高收入国家更高.

Although timing of parturition is influenced by many non-genetic risk factors, including parity(母亲的胎数), maternal stress(母亲的紧张状态), smoking, urogenital infection(泌尿系统的感染), educational attainment(受教育程度), and socioeconomic status(社会经济程度), there is compelling evidence for a substantial genetic impact.


### 定义

* preterm: < 34 weeks   
* preterm: < 34 weeks
* postterm: >= 42 weeks

### 一些pregnancy公开数据库

* Early Growth Genetics Consortium https://egg-consortium.org/
* Integrative Psychiatric Research (iPSYCH) study https://ipsych.au.dk/about-ipsych/
* Genomic and Proteomic Network for Preterm Birth Research (GPN) https://www.ncbi.nlm.nih.gov/projects/gap/cgi-bin/study.cgi?study_id=phs000714.v1.p1

这些数据库大部分是关于基因组学的,可以到时候考虑用它做个验证什么的.

parturition(分娩)

### 文章总结:












