---
title: 英语学习
author: Xiaotao Shen
date: '2019-10-29'
slug: english-study
categories:
  - life
tags:
  - Blog
image:
  caption: ''
  focal_point: ''
output:
  blogdown::html_page:
    toc: true
    number_sections: true
---

这篇博客用来记录在美国跟美国人打交道的时候学到的英语,包括口语,邮件,书面和文章等等.

# Email

## Fare thee well (再会吧)

Hi everyone,

I’m excited and surprised to announce that I have accepted an offer to become the xxx at xxx. My last day at Stanford will be Friday, Nov 15.

After nearly twelve years at Stanford – the last eight in xxx – I’m filled with gratitude and pride to have been even a small part of the remarkable work you amazing people do every day. It has been the privilege of a lifetime to work with so many dedicated and talented and tireless and splendid people. I’ve benefitted from your knowledge, your creativity, your patience, friendship, and faith, and I’ve received far more than I could ever repay. My endless thanks to you all.

Yours,

xxx

这封邮件是系里面的一位工作人员要离开Stanford发给大家的再见信.感觉写的非常好.值得我好好学习.

## November 3, 2019 Request

Hi Jasper,

I put you on the schedule for this upcoming Sunday. I will be out of town, so please let me know as soon as possible if you are able to help out(这个用法第一次见`help out`). Remember to come by (类似于stop by) 6:30 to welcome people, and stick around (逗留) for a few minutes afterward to help any newcomers get plugged in(这个第一次见这个意思). Let me know if you have any questions! Thanks for all you do.

Thanks,

xxx

这封邮件是一个组织的周末聚会要求我过去当志愿者的.学到的知识,包括: help out, come by, stick around, get plugged in等.

## Thanksgiving

You are invited to xxx’s Thanksgiving Potluck `(家常便饭,美分自带一个菜的家庭聚会)` at his home ~ xxx November 28, 2019.

If you are able to attend please let us know what **potluck item** you would like to bring & if you plan to come for football (to play or cheer from the sidelines`(球场的边线,场边)`).

Please use the following link to sign up:

## Desktop PC fixing

Hi xxx,

We were able to find the drivers for the Desktop and we will start the re-imaging process.

I will let you know when this is completed.

Thank you.
xxx
Field Service Technician
Technology & Digital Solutions
Stanford Health Care

## Postdoc hike

Hello Postdocs,

What: SURPAS Hike 

When: Sunday, November 17, 2019 

9 am at the Stanford Oval (for carpools), 9:45 am at the trailhead

Where: Sweeny Ridge Loop

*****

We will hike the Sweeny Ridge loop near Pacifica. This is a 5.7 mile intermediate loop hike with 954 feet of elevation (海拔) and 360-degree views. We should be able to complete the hike in around (更适合使用around而不是about) 3-4 hours. This hike is dog friendly! 

Please register here (more details will be provided before the hike)

More info: Route description

*Please consider driving (`conder doing sth`) a carpool for your fellow postdocs that (感觉更应该是`who`?) don’t have cars, we will give you priority in signing up. You can drive a carpool from San Francisco area or from Stanford.*

We will limit our group size to 20 participants, so please sign up soon and let us know if you can't make it.

--SURPAS Sports Committee

## Thanksgiving dinner

Folks,

I look forward to seeing those who are able to come.

Football at 12:30 PM, dinner at 3:00 PM

* `It is not supposed to rain` so I think that football will still be on. You might bring some extra clothes and shoes in case `you get muddy`(变得泥泞,发现`get`是万能的).

* If it is `rainy` I will post on the sign up sheet `by noon` whether we are playing or not. You can also text me at xxxx.

* `It is supposed to be a bit cold` so `likely` we will eat inside this year, but we will have some heaters for those who like the cool air.

Please `do`(一定,确保,务必,强调的感觉) sign up to help with the `head count`(点人头,好口语化的说法).
See you soon.

Best,

xxx

学到的内容: 

* It is (not) supposted to do something: 应该不会发生什么事情.

* It is rainy: 下雨天

* head count: 点人头,记人数.


# Oral communication

## `A`的发音

已知分不清`A`什么时候是`æ`的发音,什么时候`e`的发音.后来问一个朋友,他说`一般`长单词是`æ`,短单词是`e`.比如"Ada",音标为`/e di e/ `,读音为[/e di e/](https://translate.google.com/?source=gtx#view=home&op=translate&sl=en&tl=zh-CN&text=ada).而"Apple",音标为` /ˈæpl/`读音为[/ˈæpl/](https://translate.google.com/?source=gtx#view=home&op=translate&sl=en&tl=zh-CN&text=apple).

# 日常用品单词

## 胶带

胶带叫做tape,透明胶带叫做Scotch tape.
