---
title: ggplot2扩展之黑暗主题
author: Xiaotao Shen
date: '2019-10-25'
slug: ggplot2-dark-theme
categories: []
tags: []
image:
  caption: ''
  focal_point: ''
output:
  blogdown::html_page:
    toc: true
    number_sections: true
---

今天介绍一个`ggplot2`的扩展包,也是一个主题包,叫做`ggdark`.

### 安装


```{r}
#可以直接从cran安装
# if(!require(ggdark)){
#  install.packages("ggdark") 
# }
#也可以从github安装
# if(!require(ggdark)){
#  devtools::install_github("nsgrantham/ggdark")
# }
```

### 使用

`ggdark`中的函数可以分为两大类,一类就是提供与`ggplot2`主题相对应的暗黑模式.

```{r}
library(ggdark)
library(ggplot2)

p <- 
  ggplot(diamonds) + 
  geom_point(aes(carat, price, color = cut)) + 
  scale_y_continuous(label = scales::dollar) +
  guides(color = guide_legend(reverse = TRUE)) +
  labs(title = "Prices of 50,000 round cut diamonds by carat and cut",
       x = "Weight (carats)",
       y = "Price in US dollars",
       color = "Quality of the cut")
p

#使用ggdark的各种暗黑主题
p + ggdark::dark_theme_bw()

p + ggdark::dark_theme_classic()

p + ggdark::dark_theme_dark()

p + ggdark::dark_theme_gray()

p + ggdark::dark_theme_light()

p + ggdark::dark_theme_linedraw()

p + ggdark::dark_theme_minimal()

p + ggdark::dark_theme_test()

p + ggdark::dark_theme_void()

```

### 制作自己的暗黑主题

对于任意其他的主题,只需将主题放入到`dark_mode()`函数中,就可以将其转变为暗黑款的主题.

```{r}
ggdark::invert_geom_defaults()  # change geom defaults back to black

# if(!require(gapminder)){
#   install.packages("gapminder")
# }
library(gapminder)

p <- 
  ggplot(subset(gapminder, continent != "Oceania")) +
  geom_line(aes(year, lifeExp, group = country, color = country), lwd = 1, show.legend = FALSE) + 
  facet_wrap(~ continent) +
  scale_color_manual(values = country_colors) +
  labs(title = "Life expectancy has increased worldwide")

# if(!require(ggthemes)){
#   install.packages("ggthemes")
# }
library(ggthemes)

p + theme_fivethirtyeight()

##暗黑版主题
p + dark_mode(theme_fivethirtyeight())
```

