---
title: Mac使用summary
author: Xiaotao Shen
date: '2020-03-07'
slug: 
categories:
  - Mac
tags:
  - Blog
  - Chinese
image:
  caption: ''
  focal_point: ''
output:
  blogdown::html_page:
    toc: true
    number_sections: true
---

# Mac常用快捷键

* `command + space`:打开spotlight

* `command + tab`: 切换应用.

* `command + q`:需要长按q,关闭当前应用.注意finder不能使用该快捷键关闭.

* `command + c`:拷贝

* `command + v`:粘贴

* `command + option + v`:复制之后粘贴,相当于剪切.

* `command + n`:在当前应用下新建一个该应用的切口.

* `command + t`:在当前应用下新建标签页.

* `command + f`:查找.

* `command + option + f`:在chrome浏览器中定位到搜索栏.

* `ctl + command + f`:当前应用最大化,再点击一次,恢复到最大化之前.

* `command + m`:当前应用最小化,不推荐使用,因为没有快捷键可以让其恢复.

* `command + h`:隐藏当前应用.

* `command + option + h`:隐藏出当前应用外的其他所有应用.

* `command + ,`: 打开当前应用的偏好设置.

* `command + w`:关闭当前标签页.

* `command + Option + w`:关闭当前应用的所有标签页.

* `command + o`:打开文件

* `command + s`:保存文件

* `command + Shift + s`:文件另存为

* `command + delete`:删除文件.

* `command + shift + t`:chrome下重新打开刚才关闭的tab.

* `comand + shift + [`: 同一个应用中的标签页向前切换.

* `comand + shift + ]`: 同一个应用中的标签页向后切换.

* `ctl + space`:切换输入法.

* `option + command + space`:打开finder.

* `command + i`:显示文件或者文件夹信息.

* `command + ~`:在同一个应用的多个窗口间快速切换.

# space和desktop

跟windows一样,mac也有桌面,可以通过新建桌面,然后将不同的应用放在其中.从而让自己的工作比较有条理.但是注意,在mac中,如果你将一个应用最大化,那么该应用就会变成一个space,这个space是和desktop平行的.所以不推荐最大化,最好是使用将应用使用整个屏幕.

* `ctl + up`:显示所有的desktop和space,这些显示在屏幕最顶端.而当前desktop的所有应用显示在下方.

* `ctl + down`:显示当前应用的所有窗口.

* `ctl + left`: 向左切换desktop和space.

* `ctl + right`:向右切换desktop和space.

* `ctl + s`:保存.

* 按住option,然后左上角最大化按钮会变为加号,这就是适用屏幕按钮.

# 分割屏幕

如何将两个应用同时平铺在屏幕中,方便左右对照或者如拷贝文件等.

* 首先将某个应用最大化,也就是创建一个新的space,可以适用快捷键`ctrl + comamnd + f`, 然后进入到misson control界面,然后将另外一个应用拖到该space下即可.


# 截图

* `shift + command + 3`:全屏截图

* `shift + command + 4`:选择区域截图.


# Mac touchpad常用手势操作

## 单指

* 单指click:相当于鼠标左击.

* 单指double click:鼠标双击.

## 双指

* 双指轻点:鼠标右键.

* 双指各个方向滑动:鼠标滚轮.

## 三指

* 三指选择:鼠标按住左键然后拖拽选择.

## 四指

* 四指并排向左或者右:切换space和desktop.

* 四指并排向上:mission control.

* 四指并排向下:显示当前应用的所有窗口.

## 五指

* 五指向内聚拢: 显示所有程序.

* 五指向外发散: 显示桌面.