---
title: Maternal urinary metabolic signatures of fetal growth and associated clinical and environmental factors in the INMA study文献阅读总结
author: Xiaotao Shen
date: '2019-11-01'
slug: ''
categories:
  - literature
tags:
  - Academic
image:
  caption: ''
  focal_point: ''
output:
  blogdown::html_page:
    toc: true
    number_sections: true
---

# Abstract

使用NMR仪器采集urine数据.一共两个cohort.两个时间点(fisrt and third trimesters of gestation).用metabolome来预测fetal growth和birth weight.

测到的东西包括:branched-chain amino acids(支链氨基酸);isoleucine(异亮氨酸),valine(颉氨酸),leucine(亮氨酸),alanine(丙氨酸)和3 hydroxyisobutyrate(羟基异丁酸)(metabolite of valine).

另外一大类就是:pregnancy-related hormone by-products of estrogens and progesterone, and the methyl donor choline.
Physical activity, as well as other modifiable lifestyle/clinical factors, such as coffee consumption, vitamin D intake, and smoking, were identified as potential sources of metabolic variation during pregnancy.First trimester metabolic phenotypes could not predict reproducibly weight at later stages of development. 

Significant reproducible maternal urinary metabolic signatures of fetal growth and birth weight are identified for the first time and linked to modifiable lifestyle factors. This novel approach to prenatal(产前的) screening, combining multiple risk factors, present a great opportunity to personalize pregnancy management management and reduce newborn disease risk in later life.


# Methods

NMR采集数据,一共1695 metabolic phenotypes.

Exploratory metabolic profiling offers a powerful means of capturing systems-level information that re- flects both maternal genetic and environmental influ- ences, hence helping to elucidate metabolic disturbances and pathways associated with fetal outcomes.

This study aimed to (1) characterize the maternal urinary metabolome throughout pregnancy, (2) identify maternal metabolic signatures of fetal growth in two subcohorts, (3) explain potential sources of variation in metabolic profiles based on lifestyle and clinical data, and finally (4) to determine the individ- ual importance of metabolic signatures versus other maternal


## Study population

The women were interviewed twice during pregnancy (in the first and third trimesters of gestation) to obtain infor- mation about their sociodemographic characteristics and lifestyle variables. The urine samples were collected in the same interview in the morning (spot samples). The urine samples were collected in the same interview in the morning (spot samples). 所以一共有两个时间点.分别在first trimester and third trimesters.时间为**12.4 ± 1.2**和**33.9 ± 1.3** weeks.

## Definition of the fetal and birth measurements

Fetal weight(FW)就是使用ultrasound对胎儿的几个指标进行测量(详细指标见下面内容),然后使用`Hadlock`公式进行计算,可以得出胎儿的体重.

然后下面一个概念就是`fetal growth score`.

下面是原文:

Fetal growth scores or standard deviation scores (z- scores) were obtained using longitudinal growth curves calculated for each individual adjusting for constitutional factors known to affect fetal growth (i.e., maternal age, height, parity, pre-pregnancy weight, country of origin, father’s height, and fetal sex).

推测做法:

对于每一个母亲,使用胎儿的体重(fetal weight,FW)作为因变量,然后其他的一些因素,比如maternal age等等作为cofounding factor,然后进行回归,剩余的残差就是矫正过后的fetal growth score.

协变量:

Gestational age was calculated from the date of the last menstrual period (LMP) which was self-reported and was confirmed using ultrasound examination in 12 wk of gestation. When the date did not match the ultrasound measurement estimation by 7 days or more, the gestational age was corrected using its relationship to the crown-rump length(顶臀长).

GA有两种计算方式,一种是使用孕妇自己报告的最后一次月经的第一天开始算起,整个怀孕周期为280天.10个妊娠月(每个妊娠月为28天).另外一种方法是使用ultrasound在12周的数据进行反推.如果两种方法的误差不在一周内,`则以哪种为准呢?`如果误差在大于一周,则使用他们与crown-rump length(顶臀长)的关系进行矫正(`如何矫正?`).

Fetal growth score是使用longitudinal growth curve来计算的,然后adjust了一些已知的能够影响fetal growth的因素,如maternal age(母亲的年龄),height(母亲的身高),parity(已生胎数),pre-pregnancy weight(怀孕前的体重),country of origin(地区),father’s height(母亲的身高),and fetal sex(胎儿性别).

这个值是一个标准化后的值.(standard deviation scores,z-scores).

没有矫正后的z-score.

date of conception:妊娠期.

Gestational age(孕龄)was established by using crown–rump length when the calculated date of conception differed from the fetal age based on the subject’s self-reported last menstrual period by 7 days or more.


## Metabolic profiling by NMR

一共鉴定到64个代谢物,其中47个fully identified.

## Statistical analysis

### Step 1. Identify main sources of metabolic variation between first and third trimesters of gestation

PCA和OPLSA用来观察first and third trimester gestation的整体差异.

### Step 2. Identify metabolites associated with fetal growth

对于所有的metabolite数据,首先将其进行log transformation.然后将fetal growth score作为因变量,metabolite作为自变量,而采样时间作为confounding factor进行multivarite linear regression.得到的每一个metabolite的coefficient乘以1.5的作为当该metabolite level提高50%时其对fetal growth score的影响(`没有太懂?`).

Regression coefficients are presented as a percent of change in the z-score of each fetal growth measure.

### Step 3. Assess the extent to which the metabolite panel associated with fetal growth can be explained by known growth-related factors from epidemiological and clinical data

探究哪一些的metaboloite-fetal relationshi可以被一些已知的epidemiological和clinical data所解释.

作者考虑了以下已知的和fetal growth相关的参数:

maternal clinical parameters.

materna lifestyle in third trimester.

dietary intake in third trimester.

sociodemographic characteristics (社会人口特征).

一共有38个信息.详细信息请请见该[表格](https://office365stanford-my.sharepoint.com/:x:/r/personal/shenxt_stanford_edu/_layouts/15/Doc.aspx?sourcedoc=%7BE1FAE2E0-2B7D-4600-A1E3-2EC7B2391350%7D&file=41467_2019_11881_MOESM4_ESM.xlsx&action=default&mobileredirect=true).

将metabolite和maternal parameters进行spearman correlation的计算,然后化作crios plot(只保留p adjust < 0.05, FDR矫正).


In addition, correlation adjusted scores (CAR scores) were used to measure the correlation between metabolite levels and all the Mahalanobis decorrelated predictors in one model (growth-related factors selected from epidemiological and clinical data) as implemented in the R-package ‘care’

这段话没有看懂.

什么是correlation adjusted scores?

### Step 4. Determinants of birth weight: a variance decomposition analysis




